accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('edit', views.edit, name='edit'),
    path('edit-passwd', views.edit_passwd, name='edit-passwd'),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login',
    ),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('register/', views.register, name='register'),
]

core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

simplemooc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include(('core.urls', 'core'), namespace='core')),
    path(
        'accounts/',
        include(('accounts.urls', 'accounts'), namespace='accounts'),
    ),
    path(
        'courses/', include(('courses.urls', 'courses'), namespace='courses')
    ),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/models.py
import re

from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    UserManager,
)
from django.core import validators
from django.db import models


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Username',
        max_length=30,
        unique=True,
        validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+--]+$'),
                'The username can only contain letters, digits or the following characters: @/./+/-/_',
                'invalid',
            )
        ],
    )
    name = models.CharField('Name', max_length=150, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Is Staff?', blank=True, default=False)
    is_active = models.BooleanField('Is Active?', blank=True, default=True)
    date_joined = models.DateTimeField('Date Joined', auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        # full_name = f'{self.first_name} {self.last_name}'
        return str(self)

    def get_short_name(self):
        return self.name

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirm your Password', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                'The password confirmation is wrong',
            )

        return password2

    def save(self):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.save()

        return user

    class Meta:
        model = User
        fields = ['username', 'email']


class EditAccountForm(forms.ModelForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = User.objects.filter(email=email).exclude(
            pk=self.instance.pk
        )

        if queryset.exists():
            raise forms.ValidationError('Email already being used!')

        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import redirect, render

from accounts.forms import EditAccountForm, RegisterForm


@login_required
def dashboard(req):
    template_name = 'dashboard.html'
    return render(req, template_name)


@login_required
def edit(req):
    template_name = 'edit-profile.html'
    context = {}

    if req.method == 'POST':
        form = EditAccountForm(req.POST, instance=req.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=req.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=req.user)

    context['form'] = form

    return render(req, template_name, context)


@login_required
def edit_passwd(req):
    template_name = 'edit-passwd.html'
    context = {}

    if req.method == 'POST':
        form = PasswordChangeForm(data=req.POST, user=req.user)

        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = PasswordChangeForm(user=req.POST)

    context['form'] = form
    return render(req, template_name, context)


def register(req):
    template_name = 'register.html'

    if req.method == 'POST':
        form = RegisterForm(req.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(req, user)
            return redirect('core:home')
    else:
        form = RegisterForm()

    context = {'form': form}

    return render(req, template_name, context)

accounts/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                <li><a href="#">Curso 1</a></li>
                <li><a href="#">Curso 2</a></li>
                <li class="pure-menu-heading">Minha Conta</li>
                <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                <li><a href="{% url 'accounts:edit-passwd' %}">Editar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %}
            <p><strong>Nome</strong>: {{ user }} </p>
            <p><strong>E-mail</strong>: {{ user.email }} </p>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/edit-passwd.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit-passwd' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="post">
    {% csrf_token %}
    {% if success %}
    <p>A sua senha foi alterada com sucesso</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
        </div>
    </fieldset>
</form>
{% endblock %}

accounts/templates/edit-profile.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
{{ block.super }}
<li>/</li>
<li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
<form class="pure-form pure-form-stacked" method="POST">
    {% csrf_token %}
    {% if success %}
    <p>Your data was updated!</p>
    {% endif %}
    <fieldset>
        {{ form.non_field_erros }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Join Simple Mooc</h2>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Register</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock %}